language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - echo 'output_buffering = Off' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --dev --prefer-source
  - ./bin/ci/before_build.sh

script: make test

services:
  rabbitmq
